Гасанов Амин .Task 4
only-digital/internship-tasks pull request #152
Opened 2023-10-05 16:54 UTC by lolotron02

Переключение кнопки "Отправить" на "Отправлено" хотелось бы выполнить заменой HTML-кода, а не, как у меня сейчас, просто при помощи display:none. Однако я не нашел способа, как импортировать status из fetch в Pug файл, чтобы там написать условие if-else для button и sucsses-placeholder. Использование innerHTML не подходит, так как мне кажется неправильным писать HTML-код при работе с препроцессором Pug.

2023-10-06 04:38 UTC, lolotron02 commented
В последнем комите  изменение button на sucsses-placeholder реализовано при помощи javascript InnerHTML а не display:none,display:flex как в предыдущем комите.

2023-10-09 09:10 UTC, VitoBravis requested changes
Надо поправить `loader

2023-10-09 09:10 UTC, VitoBravis commented on src/app/js/base/component.js
> +
Нежелательная модификация базового компонента
Класс `Component` является родительским классом для всех существующих в проекте компонентов. Добавлять в него функционал, который не является общим для всех компонентов - лишнее

2023-10-09 09:10 UTC, VitoBravis commented on src/app/js/base/component.js
>      getElements = (name) => {
Нежелательное удаление документации
Это не просто комментарии к методу, это документация оставленная в формате [JsDoc](https://jsdoc.app/). 
Она необходима для таких базовых методов/функций/классов

2023-10-09 09:10 UTC, VitoBravis commented on src/app/js/base/component.js
> +        this.loader = document.querySelector(`.loader`);
Нежелательная модификация базового компонента
Компонент не должен управлять элементами за пределами своего компонента. Это нарушает принцип изолированности компонентов
Элемент `loader` существует в единственном экземпляре, но каждый существующий компонент будет искать и работать с одним и тем же элементом. Это лишнее дублирование

2023-10-09 09:10 UTC, VitoBravis commented on src/components/footer/footer.js
> +            this.inputCt.classList.add("input-ct__alert_active");
Сервер вместе с ответом присылает объект. В этом объекте поле `message` содержит описание конкретной ошибка сервера.
Лучше выводить её вместо статичного сообщения об ошибке

2023-10-09 09:10 UTC, VitoBravis commented on src/components/loader/loader.scss
> +    width: 100vw;
`loader` не должен полностью блокировать взаимодействие со страницей.
Например, количество просмотров и откликов не является обязательным для просмотра вакансии

2023-10-10 07:15 UTC, lolotron02 commented
Надеюсь я правильно понял какой loader от меня хотели. Откатил класс Component до исходной версии , сделал loader локальными для header и footer и не на всю страницу а лишь на часть которая грузится (в footer не все заменяется на loader а лишь кнопка, если необходима весь form заменить то это дело двух строк) Так же хотел сделать появление и пропажу loader при помощи InnerHTML и remove() но не стал так как при применения innerHTML есть необходимость заново инициировать все переменные внутри form.Есть пару идей как можно было бы обойти эту проблему но там уже слишком много всего надо было бы переписать так что просто сделал при помощи disaplay:none и display:block появление и пропажу loader .

2023-10-13 07:57 UTC, VitoBravis approved these changes
Зачтено 👍

2023-10-13 07:57 UTC, closed without merging