RomanZhadanov
only-digital/internship-tasks pull request #251
Opened 2023-11-01 09:37 UTC by ZhadanovRoman

2023-12-24 21:27 UTC, dislav requested changes
Требуется внести исправления в указанных местах (⛔️)

2023-12-24 21:27 UTC, dislav commented on src/components/check-button/check-button.js
> +        localStorage.setItem('checkCount',JSON.stringify(this.count++))
⛔️ **Необходимы исправления**

Не совсем правильный подход для определения состояния `checked`. Правильным способом является обращение к элементу `input` (в примере `input` это `e.target`, а `checked` его состояние нажатия):

```js
class CheckButton extends Component {
    checkBox;

    constructor(element) {
        super(element);
        
        this.checkBox = this.getElement('inpt');
        this.checkBox.addEventListener('change',this.onCheck)
      
    }
        
    onCheck = (e) => {
        console.log(e.target.checked);
    }   
}
```

Еще более неправильным способом является запись такой переменной в `localStorage`.

Что будет если на странице будет несколько таких форм? - При клике в одной форме на чекбокс запишется переменная, а при клике на другой она перезапишется на другое значение. Это приведет к логическим ошибкам, так как переменная не будет являться локальной для компонента формы.

Лучше перенести логику получение `checked` в компонент `feedback`.

2023-12-24 21:27 UTC, dislav commented on src/components/feedback/feedback.js
> +        this.inptMail = document.getElementById('email');
В случае одной формы ок, а если их будет несколько, то придется придумывать уникальное название `id` для каждой?

Лучше искать инпуты по классу внутри формы и не заморачиваться с `id`.

2023-12-24 21:27 UTC, dislav commented on src/components/feedback/feedback.js
> +            this.inptBlock[0].firstChild.style.opacity = '0';//прячем svg
Скрыть или показать элемент можно при помощи класса. В текущем случае это класс модификатор состояния ошибки (например, `feedback__inpt-block_error`). Поскольку данный класс добавляется самой обертке инпута (`feedback__inpt-block`), то с помощью него можно будет легко застилизовать ошибку самого инпута, лейбла и текста, без необходимости делать это через JS.

----

Нужно стараться как можно меньше использовать инлайновые стили. Недостатки инлайновых стилей:

- **Смешивание структуры и стиля** (Инлайновые стили внедряются непосредственно в HTML-разметку, что может смешивать структуру документа с его визуальным представлением.)
- **Трудность переиспользования** (Инлайновые стили не могут быть легко переиспользованы между различными элементами и страницами.)
- **Неудобство в работе с CSS-правилами** (Инлайновые стили не предоставляют удобства и гибкости работы с мощными возможностями CSS, такими как псевдоклассы, псевдоэлементы, медиазапросы и т. д.)
- **Увеличение размера HTML-кода** (Внедрение стилей непосредственно в HTML увеличивает размер самого HTML-кода, что может снизить производительность загрузки страницы, особенно при большом количестве элементов с инлайновыми стилями.)

2023-12-24 21:27 UTC, dislav commented on src/components/feedback/feedback.js
> +        if (JSON.parse(localStorage.getItem('checkCount')) % 2 === 0) {//проверка на чекед
⛔️ **Необходимы исправления**

Нужно получать состояние `checked` напрямую через инпут чекбокса. Для этого в шаблоне `pug` можно добавить класс к кнопке, чтобы проще можно было его найти.

```pug
+check-button().feedback__checkbox
```

И найти элемент:

```js
// constructor
this.checkbox = this.getElement('checkbox'); // находим обертку
this.checkboxInput = this.checkbox.querySelector('input'); // внутри обертки получаем сам input

// onSubmit
console.log(this.checkboxInput.checked); // true или false
```

2023-12-24 21:27 UTC, dislav commented on src/components/feedback/feedback.js
> +            fetch('/form', {
Заместо цепочки промисов `then` лучше использовать [async/await](https://learn.javascript.ru/async-await), это повышает читаемость кода.

2023-12-24 21:27 UTC, dislav commented on src/components/feedback/feedback.js
> +                body: JSON.stringify({
⛔️ **Необходимы исправления**

Файлы также должны отправляться в запросе.

Для отправки бинарных файлов необходимо использовать [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData), так как их нельзя преобразовать в строку при помощи `JSON.stringify`.

2024-01-10 09:41 UTC, ZhadanovRoman commented on src/components/feedback/feedback.js
> +                body: JSON.stringify({
Добрый день ) Сервер не принимает данные обработанные в formData()

2024-01-10 10:58 UTC, ZhadanovRoman commented on src/components/feedback/feedback.js
> +                body: JSON.stringify({
Все остальное исправил )

2024-01-17 08:55 UTC, dislav approved these changes
Зачтено 🚀

2024-01-17 08:55 UTC, dislav commented on src/components/feedback/feedback.js
> +        this.checkBox = document.querySelector('.check-button__inpt');
> Делая поиск в `document` найдется первый элемент с текущем селектором на всем сайте, а не внутри текущей формы.

Основной компонент (см. `src/app/js/base/Component`) от которого наследуется `Feedback` имеет свои методы и свойства, которые можно использовать в текущем классе.

![Снимок экрана 2023-12-27 в 23 06 51](https://github.com/only-digital/internship-tasks/assets/48628992/68788d7d-077c-4922-b683-91f556237b4f)

Поэтому чтобы сделать поиск внутри текущей формы, нужно делать так:

```js
this.checkBox = this.root.querySelector('.check-button__inpt');
```

2024-01-17 08:55 UTC, closed without merging