Лев Серегин
only-digital/internship-tasks pull request #266
Opened 2023-11-17 07:29 UTC by sereginlev

2023-12-27 22:25 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️
Остальные по желанию

2023-12-27 22:25 UTC, dislav commented on src/hooks/useSearch.js
> +		return data.filter(({ title, text }) => title.toLowerCase().includes(searchValue.toLowerCase()) || text.toLowerCase().includes(searchValue.toLowerCase()));
`searchValue.toLowerCase()` можно вынести в переменную, чтобы не дублировать код

2023-12-27 22:25 UTC, dislav commented on src/components/task/task.jsx
> +	const [taskStatus, setTaskStatus] = useState(isCompleted);
⛔️ **Необходимы исправления**

Нужно изменять не локальное состояние `isCompleted` в компоненте, а общее состояние `tasksList`, которое находится в компоненте `content.jsx`

Можно прокидывать функцию в текущий компонент (например, `onToggleTask`) и по аналогии с `onSetIndex` прокидывать `index` для удаления.

2023-12-27 22:25 UTC, dislav commented on src/components/content/content.jsx
> +							onSetIndex={handleRemoveTask}
Рекомендуется называть переменные/пропсы так, чтобы было понятно какую суть они отражают. `onSetIndex` логичнее назвать - `onRemoveTask`.

2024-01-05 10:09 UTC, sereginlev commented on src/components/task/task.jsx
> +	const [taskStatus, setTaskStatus] = useState(isCompleted);
Внес исправления.

2024-01-09 19:42 UTC, dislav requested changes
*

2024-01-09 19:42 UTC, dislav commented on src/components/content/content.jsx
> +		const newTasksList = tasks.map((task, idx) => {
⛔️ **Необходимы исправления**

Нужно менять не изначальные данные, а само состояние `tasksList` (пробегаться `map` по `tasksList`).

2024-01-09 19:44 UTC, dislav approved these changes

2024-01-09 19:45 UTC, dislav approved these changes
Зачтено 🚀

2024-01-09 19:45 UTC, dislav commented on src/components/content/content.jsx
> +		const newTasksList = tasks.map((task, idx) => {
Нужно менять не изначальные данные, а само состояние `tasksList` (пробегаться `map` по `tasksList`).

2024-01-09 19:45 UTC, closed without merging