task-6: Александр Шпанов
only-digital/internship-tasks pull request #267
Opened 2023-11-18 11:43 UTC by Whittun

2023-12-27 20:59 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️
Остальные по желанию

2023-12-27 20:59 UTC, dislav commented on src/pages/index.js
> +            <WorkingArea/>
⛔️ **Необходимы исправления**

В задании `json` файл используется в виде моков, которые запрашиваются в функции `getIndexPage`. Поэтому нужно работать с пропсами, которые вернулись на страницу, а не с файлом `json` напрямую.

В компонент нужно пробрасывать задачки и там уже работать с ними:

```jsx
<WorkingArea tasks={props.tasks} />
```

2023-12-27 20:59 UTC, dislav commented on src/components/todoList/todoList.jsx
> +import data from '../../../data/index.json';
⛔️ **Необходимы исправления**

Задачки должны приходить в данный компонент в пропсах.

2023-12-27 20:59 UTC, dislav commented on src/components/todoList/todoList.jsx
> +    modifiedTasks.forEach((task, i) => {
Реализация при помощи метода `map`:

```js
const tasksWithId = data.tasks.map((task, index) => ({ ...task, id: index }));
```

2023-12-27 20:59 UTC, dislav commented on src/hooks/useSearch.js
> +  const [filteredTasks, setFilteredTasks] = useState(tasks)
⚠️ Желательно поправить

Можно обойтись без дополнительного состояния. Хуки в React по умолчанию "цепляются" к состояниям и методам жизненного цикла. Другими словами при обновлении какого-то состояние, произойдет какое-то вычисление в хуке.

Подумай как можно обойтись без дополнительного стейта.

2023-12-27 20:59 UTC, dislav commented on src/hooks/useSearch.js
> +      task.title.toLowerCase().includes(searchText.toLowerCase())
⛔️ **Необходимы исправления**

Поиск должен быть в том числе и по свойству `text`.

2023-12-27 20:59 UTC, dislav commented on src/components/todoList/todoList.jsx
> +                            onItemClick={(e) => {
1. Анонимные функции в `JSX` лучше выносить перед `return`, так улучшается читаемость кода
2. Можем получать `id` задачки как-то еще? (не обращаясь к `e.target.id`)

2023-12-27 20:59 UTC, dislav commented on src/components/todoList/todoList.jsx
> +                                setTasks([...tasks.slice(0, id), { ...tasks[id], isCompleted: !tasks[id].isCompleted }, ...tasks.slice(id + 1)])
Можно сделать смену состояния через предикат, который хранит текущее состояние:

```js
setTasks((state) =>
  state.map((task) => {
    if (task.id === id) {
      return {
        ...task,
        isCompleted: !task.isCompleted,
      };
    }

    return task;
  })
);
```

2023-12-27 20:59 UTC, dislav commented on src/components/todoList/todoList.jsx
> +                                setTasks(
Смена состояния через предикат:

```js
setTasks((state) =>
  state.filter((task) => task.id !== +e.target.parentNode.id)
);
```

2024-01-03 16:29 UTC, Whittun commented
Внёс обязательные правки и некоторые дополнительные, большое спасибо вам за ревью!

2024-01-09 20:07 UTC, dislav approved these changes
Зачтено 🚀

2024-01-09 20:07 UTC, dislav commented on src/components/todoList/todoList.jsx
> +        const id = +e.target.id
В функцию `id` лучше прокидывать аргументом:

```js
const todoItemHandler = (id) => {...}
```

2024-01-09 20:07 UTC, dislav commented on src/components/todoList/todoList.jsx
> +                    id: i,
Необязательно заново передавать `id`, в состоянии `tasks` он уже есть.

2024-01-09 20:07 UTC, dislav commented on src/components/todoList/todoList.jsx
> +                            onItemClick={todoItemHandler}
Можно прокидывать аргумент с `id` в функцию, чтобы не получать его через `e.target.id`:

```jsx
onItemClick={() => todoItemHandler(item.id)}
```

2024-01-09 20:07 UTC, dislav commented on src/components/todoList/todoList.jsx
> +                            onButtonClick={todoItemButtonHandler}
Можно прокидывать аргумент с `id` в функцию, чтобы не получать его через `e.target`:

```jsx
onButtonClick={e => todoItemButtonHandler(e, item.id)}
```

2024-01-09 20:08 UTC, closed without merging