Муравьев Виктор task5
only-digital/internship-tasks pull request #272
Opened 2023-11-30 10:07 UTC by santaz0r

2023-12-28 19:45 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️
Остальные по желанию

2023-12-28 19:45 UTC, dislav commented on src/components/text-field/text-field.js
> +    this.textAreaElement = document.querySelector(".my-textarea");
Основной компонент (см. `src/app/js/base/Component`) от которого наследуется `TextField` имеет свои методы и свойства, которые можно использовать в текущем классе.

![Снимок экрана 2023-12-27 в 23 06 51](https://github.com/only-digital/internship-tasks/assets/48628992/68788d7d-077c-4922-b683-91f556237b4f)

Делать поиск по классу по документу ошибочно. Если на странице будет несколько `textarea` с классом `my-textarea`, то `document.querySelector('.my-textarea')` найдет самый первый из них. Чтобы логика компонентов была изолированной в базовом компоненте у нас есть переменная `root` в которой хранится текущий компонент.

> Чтобы проверить, что это неправильно, можешь в форме вывести еще один `+text-field({inputType: 'text' , label: 'Комментарий', type: 'textarea'})` и компонент начнет работать неправильно

Поэтому чтобы правильно найти элемент в рамках текущего компонента, нужно выполнять `querySelector` таким образом:

```js
this.textAreaElement = this.root.querySelector('.my-textarea');

console.log(this.root); // текущий компонент, элемент text-field
console.log(this.textAreaElement); // textarea в нужно компоненте text-field
```

2023-12-28 19:45 UTC, dislav commented on src/components/my-form/my-form.js
> +      icon.style.display = "block";
Отображением иконки можно легко рулить через класс, который бы накидывался на обертку компонента.

----

Нужно стараться меньше использовать инлайновые стили. Недостатки инлайновых стилей:

- **Смешивание структуры и стиля** (Инлайновые стили внедряются непосредственно в HTML-разметку, что может смешивать структуру документа с его визуальным представлением.)
- **Трудность переиспользования** (Инлайновые стили не могут быть легко переиспользованы между различными элементами и страницами.)
- **Неудобство в работе с CSS-правилами** (Инлайновые стили не предоставляют удобства и гибкости работы с мощными возможностями CSS, такими как псевдоклассы, псевдоэлементы, медиазапросы и т. д.)
- **Увеличение размера HTML-кода** (Внедрение стилей непосредственно в HTML увеличивает размер самого HTML-кода, что может снизить производительность загрузки страницы, особенно при большом количестве элементов с инлайновыми стилями.)

2023-12-28 19:45 UTC, dislav commented on src/components/my-form/my-form.js
> +      file: URL.createObjectURL(this.fileInput.files[0]),
⛔️ **Необходимы исправления**

Отправленный `blob` нельзя будет открыть и посмотреть после отправки, так как он создается локально в браузере (по сути как временная ячейка, куда скидывается файл и дается ссылка на него)

2023-12-28 19:45 UTC, dislav commented on src/components/my-form/my-form.js
> +        body: JSON.stringify(data),
⛔️ **Необходимы исправления**

Чтобы отправить файлы и другие данные нужно использовать [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData), тогда сервер сможет принять их и считать их.

2023-12-28 19:45 UTC, dislav commented on src/components/my-form/my-form.js
> +    this.root.addEventListener("change", () => this.checkForm());
Лучше не использовать анонимные функции, так как позже нельзя будет удалить листенер `removeEventListener`, к тому же запись будет выглядить компактне:

```js
this.root.addEventListener("change", this.checkForm);
```

2024-01-15 12:27 UTC, santaz0r commented on src/components/text-field/text-field.js
> +    this.textAreaElement = document.querySelector(".my-textarea");
исправлено

2024-01-15 12:27 UTC, santaz0r commented on src/components/my-form/my-form.js
> +      file: URL.createObjectURL(this.fileInput.files[0]),
исправил

2024-01-15 12:27 UTC, santaz0r commented on src/components/my-form/my-form.js
> +        body: JSON.stringify(data),
Изменил

2024-01-15 12:27 UTC, santaz0r commented on src/components/my-form/my-form.js
> +    this.root.addEventListener("change", () => this.checkForm());
поправил

2024-01-17 09:06 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️

2024-01-17 09:06 UTC, dislav commented on src/components/my-form/my-form.js
>            "Content-Type": "application/json",
⛔️ **Необходимы исправления**

Теперь отправленные данные выглядят так:

![Снимок экрана 2024-01-17 в 12 04 09](https://github.com/only-digital/internship-tasks/assets/48628992/32b1a49e-3820-46d5-bc52-b35ef96115cf)

Так происходит из-за того, что остались `headers` - `"Content-Type": "application/json"`
Нужно их удалить и тогда будет отправляться без проблем

2024-01-17 10:07 UTC, santaz0r commented on src/components/my-form/my-form.js
>            "Content-Type": "application/json",
Убрал

2024-01-20 12:32 UTC, dislav approved these changes
Зачтено 🚀

2024-01-20 12:32 UTC, closed without merging