Захаров Дима. Task 5
only-digital/internship-tasks pull request #275
Opened 2024-01-14 19:25 UTC by zakharovdm

2024-01-20 12:59 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️
Остальные по желанию

2024-01-20 12:59 UTC, dislav commented on src/components/feedback/feedback.js
> +    this.emailInput = document.querySelector('.input__email');
Базовый компонент (см. `src/app/js/base/Component`) от которого наследуется `Feedback` имеет свои методы и свойства, которые можно использовать в текущем классе.

![Снимок экрана 2023-12-27 в 23 06 51](https://github.com/only-digital/internship-tasks/assets/48628992/68788d7d-077c-4922-b683-91f556237b4f)

Делать поиск по документу ошибочно, так как если на странице будет несколько `textarea` с классом `input__email`, то `document.querySelector('.input__email')` найдет самый первый из них. Чтобы логика компонентов была изолированной в базовом компоненте у нас есть переменная `root` в которой хранится "обертка" текущего компонента.

Поэтому чтобы правильно найти элемент в рамках текущего компонента, можно накинуть класс `feedback__input-email` на инпут в шаблоне и выполнять поиск таким образом:

```js
this.emailInput = this.getElement('input-email');
```

2024-01-20 12:59 UTC, dislav commented on src/components/feedback/feedback.js
> +      this.labelElement.style.color = '#bcbcbc';
Лучше управлять стилями через классы

Недостатки инлайновых стилей:

- **Смешивание структуры и стиля** (Инлайновые стили внедряются непосредственно в HTML-разметку, что может смешивать структуру документа с его визуальным представлением.)
- **Трудность переиспользования** (Инлайновые стили не могут быть легко переиспользованы между различными элементами и страницами.)
- **Неудобство в работе с CSS-правилами** (Инлайновые стили не предоставляют удобства и гибкости работы с мощными возможностями CSS, такими как псевдоклассы, псевдоэлементы, медиазапросы и т. д.)
- **Увеличение размера HTML-кода** (Внедрение стилей непосредственно в HTML увеличивает размер самого HTML-кода, что может снизить производительность загрузки страницы, особенно при большом количестве элементов с инлайновыми стилями.)

2024-01-20 12:59 UTC, dislav commented on src/components/feedback/feedback.js
> +      headers: {
⛔️ **Необходимы исправления**

Из-за `headers` запрос выглядит так:

![Снимок экрана 2024-01-20 в 15 53 30](https://github.com/only-digital/internship-tasks/assets/48628992/ae171295-b273-486c-bbee-91389ea06b31)

Необходимо удалить их, тогда `fetch` будет автоматически проставлять `Content-Type`

2024-01-20 12:59 UTC, dislav commented on src/components/input/input.js
> +      this.inputWrapper.classList.add('input__wrapper--valid');
⛔️ **Необходимы исправления**

После успешной отправки формы не скидывается валидное состояние с инпутов:

![Снимок экрана 2024-01-20 в 15 57 32](https://github.com/only-digital/internship-tasks/assets/48628992/d99344c5-a739-4d2e-b58c-4bde052e5db6)

2024-01-22 20:07 UTC, zakharovdm commented on src/components/feedback/feedback.js
> +      headers: {
Я удалил, но кажется ничего не изменилось.
![image](https://github.com/only-digital/internship-tasks/assets/45212797/81e51721-3476-4205-9589-b72bb85a0065)
Или в чем проблема? Можешь объяснить подробнее пожалуйста.

2024-01-22 20:21 UTC, zakharovdm commented on src/components/input/input.js
> +      this.inputWrapper.classList.add('input__wrapper--valid');
Поправил

2024-01-22 21:03 UTC, zakharovdm commented on src/components/feedback/feedback.js
> +    this.emailInput = document.querySelector('.input__email');
Поправил

2024-01-22 21:19 UTC, zakharovdm commented on src/components/feedback/feedback.js
> +      this.labelElement.style.color = '#bcbcbc';
Спасибо, поправил

2024-01-27 12:26 UTC, dislav commented on src/components/feedback/feedback.pug
> +				input.feedback__input-policy(type='checkbox' id='policy' name='confirm' required=true disabled="disabled").feedback__policy-input
⛔️ **Необходимы исправления**

У чекбокса по умолчанию выставлено состояние `disabled` из-за чего клик по нему не срабатывает

2024-01-27 12:26 UTC, dislav commented on src/components/feedback/feedback.js
>      if (this.policyCheckbox.disabled) {
⛔️ **Необходимы исправления**

Лучше отталкиваться от состояния `checked`, так как `disabled` блокирует событие `change`. К тому же состояние `disabled` немного неуместно здесь.

2024-01-27 12:26 UTC, dislav commented on src/components/feedback/feedback.js
> +      headers: {
Попробуй кликнуть сюда

![Снимок экрана 2024-01-27 в 15 25 44](https://github.com/only-digital/internship-tasks/assets/48628992/8ab32bc5-6cdf-400e-a3fb-7eaa8c5d473a)

2024-01-27 12:28 UTC, dislav commented on src/components/input/input.js
> +      this.inputWrapper.classList.add('input__wrapper--valid');
⛔️ **Необходимы исправления**

После отправки не скидывается состояние документов

![Снимок экрана 2024-01-27 в 15 27 31](https://github.com/only-digital/internship-tasks/assets/48628992/f7e48b2a-bd20-4beb-9d46-6bc33af2437b)

2024-01-27 12:29 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️
Также посмотри комменты к предыдущим ошибкам

2024-01-28 19:36 UTC, zakharovdm commented on src/components/feedback/feedback.pug
> +				input.feedback__input-policy(type='checkbox' id='policy' name='confirm' required=true disabled="disabled").feedback__policy-input
Поправил

2024-01-28 19:43 UTC, zakharovdm commented on src/components/feedback/feedback.js
> +      headers: {
Увидел, спасибо. Ну то есть это норм практика, не проставлять headers при отправке данных сервер?

2024-01-28 20:40 UTC, zakharovdm commented on src/components/input/input.js
> +      this.inputWrapper.classList.add('input__wrapper--valid');
Поправил

2024-01-28 20:53 UTC, zakharovdm commented on src/components/feedback/feedback.js
>      if (this.policyCheckbox.disabled) {
Я это вообще снес сейчас, так как моя задумка не работает. Я хотел ловить состояние инпута, чтобы изменять цвет лэйбла.

2024-01-29 16:49 UTC, dislav commented on src/components/feedback/feedback.js
> +      headers: {
> Увидел, спасибо. Ну то есть это норм практика, не проставлять headers при отправке данных сервер?

Да, [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_a_file) автоматически проставляет `headers` для `FormData`

2024-01-29 16:52 UTC, dislav approved these changes
Зачтено 🚀

2024-01-29 16:52 UTC, closed without merging