Захаров Дима Task 6
only-digital/internship-tasks pull request #278
Opened 2024-01-31 12:16 UTC by zakharovdm

2024-02-04 11:57 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️
Остальные по желанию

2024-02-04 11:57 UTC, dislav commented on data/index.json
> +            "id": 0,
⛔️ **Необходимы исправления**

По условию задания запрещено изменять структуру объекта

> 1. На страницу приходят данные описанные в файле /data/index.json, содержимое файла можно изменять по своему усмотрению, **но без изменения структуры объекта**

Можно добавлять `id` при добавлении списка задачек в `useState`, либо завязываться на `index` задачки

2024-02-04 11:57 UTC, dislav commented on src/components/hooks/use-search.js
> +      item.title.toLowerCase().includes(searchQuery.toLowerCase().trim()) ||
Небольшая придирка - `searchQuery.toLowerCase().trim()` можно было вынести в переменную, чтобы не дублировать код

2024-02-04 11:57 UTC, dislav commented on src/pages/index.js
> +  const [tasks, setTasks] = useState(props.tasks);
⛔️ **Необходимы исправления**

Вот тут можно прокидывать таски с `id` (`id` - это `index`) или ничего не трогать и завязать функции `doneTaskHandler` и `deleteTaskHandler` на `index` задачки, например:

```js
const doneTaskHandler = (taskIndex) => {...}
```

2024-02-04 11:57 UTC, dislav commented on src/pages/index.js
> +    setTasks(newTasks);
Можно сделать смену состояния через предикат:

```js
setTasks((state) =>
  state.map((task) => {
    if (task.id === taskId) {
      return {
        ...task,
        isCompleted: !task.isCompleted,
      };
    }

    return task;
  })
);
```

2024-02-04 11:57 UTC, dislav commented on src/pages/index.js
> +      const newTasks = prevTasks.filter((task) => task.id !== taskId);
Можно упросить и сразу возвращать массив

```js
setTasks((prevTasks) => prevTasks.filter((task) => task.id !== taskId));
```

2024-02-04 11:57 UTC, dislav commented on src/components/inputSearch/inputSearch.jsx
> +  const [isFilled, setIsFilled] = useState(false);
Можно избавится от состояний `isFilled` и `inputValue`, так как проверку `isFilled` можно сделать отталкиваясь от `inputValue`:

```js
const isFilled = !!inputValue.length; // или input.value.length > 0
```

А состояние `inputValue` фактически у тебя находится в файле `taskList.jsx`, можно просто его сюда пробрасывать:

```jsx
const InputSearch = ({ value, onSearch }) => {
  const isFilled = !!value.length;

  const inputHandler = (evt) => {
    onSearch(evt.target.value);
  };

  const iconStyle = isFilled
    ? styled.InputSearch__iconHidden
    : styled.InputSearch__icon;

  return (...);
};
```

2024-02-04 19:48 UTC, zakharovdm commented on data/index.json
> +            "id": 0,
Поправил

2024-02-04 19:48 UTC, zakharovdm commented on src/pages/index.js
> +  const [tasks, setTasks] = useState(props.tasks);
Завязался на индекс

2024-02-04 19:53 UTC, zakharovdm commented on src/components/hooks/use-search.js
> +      item.title.toLowerCase().includes(searchQuery.toLowerCase().trim()) ||
Поправил

2024-02-05 11:56 UTC, zakharovdm commented on src/pages/index.js
> +    setTasks(newTasks);
Поправил

2024-02-05 12:01 UTC, zakharovdm commented on src/pages/index.js
> +      const newTasks = prevTasks.filter((task) => task.id !== taskId);
Поправил

2024-02-05 12:24 UTC, zakharovdm commented on src/components/inputSearch/inputSearch.jsx
> +  const [isFilled, setIsFilled] = useState(false);
Убрал состояния.
А почем здесь лучше убрать состояния?

2024-02-07 16:50 UTC, dislav commented on src/components/inputSearch/inputSearch.jsx
> +  const [isFilled, setIsFilled] = useState(false);
Просто потому что можно обойтись стандартной проверкой

2024-02-07 16:59 UTC, dislav requested changes
Требуется внести исправления в местах где указал - ⛔️

2024-02-07 16:59 UTC, dislav commented on src/pages/index.js
> +    setTasks((task, index) => {
⛔️ **Необходимы исправления**

Задачки перестали менять статус, посмотри на пример еще раз, сейчас ошибка в смене состояния

2024-02-07 18:19 UTC, zakharovdm commented on src/pages/index.js
> +    setTasks((task, index) => {
Классно я массив обходил)
Теперь должно быть все ок

2024-02-08 14:17 UTC, dislav approved these changes
Зачтено 🚀

2024-02-08 14:17 UTC, closed without merging