Анна Хижняк
only-digital/internship-tasks pull request #28
Opened 2023-09-22 09:58 UTC by AnnaKhiz

2023-09-22 11:17 UTC, VitoBravis requested changes
Надо доработать компонент `switcher-button`

2023-09-22 11:17 UTC, VitoBravis commented on src/components/button-with-border/button-with-border.scss
> +	transition: all 0.5s ease-out 0s;
Использование значения `all` для правила `transition` не рекомендуется, так как анимация будет применяться ко всем возможным свойствам. 
Это может вызвать неправильное поведение элементов и создать лишнюю нагрузку, так как будут анимироваться css-правила, анимация которых не планировалась
Лучше конкретизировать css-правила, которым нужна анимация. Это также позволит задать разное время анимации каждому css-правилу при необходимости

2023-09-22 11:17 UTC, VitoBravis commented on src/components/switcher-button/switcher-button.pug
> +	.switcher-button&attributes(attributes)
Переключатель должен переключать свое состояние. Для этого стоит использовать стандартный элемент браузера:
[`<input type="checkbox">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)

2023-09-22 13:28 UTC, AnnaKhiz commented
Исправила переключатель и транзишен

2023-09-25 10:14 UTC, VitoBravis approved these changes
Зачтено 👍

2023-09-25 10:14 UTC, closed without merging