Роман Удодов
only-digital/internship-tasks pull request #8
Opened 2023-09-19 16:50 UTC by udodovrs

2023-09-20 08:30 UTC, VitoBravis requested changes
Надо доработать верстку внутри `flex-container`

2023-09-20 08:30 UTC, VitoBravis commented on src/components/grid-container/grid-container.pug
> +                    +icon(color)
Желательно не вкладывать миксины друг в друга, это может усложнить чтение кода другими разработчиками
Лучше хранить миксины на одном уровне или в отдельных файлах:
```jade

mixin icon(color)
    // ... 

mixin block-of-grid (classBlokOfGrid, location, title, color) 
    // ...

mixin grid-container()
    section.grid-container
        +block-of-grid(/*...*/)
```

2023-09-20 13:12 UTC, udodovrs commented on src/components/flex-container/flex-container.pug
> +
Исправил, добавил верстку на flex

2023-09-20 13:12 UTC, udodovrs commented on src/components/grid-container/grid-container.pug
> +                    +icon(color)
Исправил, перенес миксины в отдельную папку

2023-09-21 09:14 UTC, VitoBravis approved these changes
Зачтено 👍

2023-09-21 09:14 UTC, closed without merging