Антон Дедяев
only-digital/internship-tasks pull request #85
Opened 2023-09-28 14:49 UTC by antonDedyaev

2023-09-29 10:11 UTC, VitoBravis requested changes
Надо сделать каждый спойлер отдельным компонентом

2023-09-29 10:11 UTC, VitoBravis commented on src/components/accordion/accordion.pug
> +				+accordion-item(val)
Лучше делать каждый спойлер отдельным компонентом, а не набор спойлеров записывать в один компонент
Так получится более явно разделить js-логику. С каждым спойлером будет возможно работать как с отдельным объектом. На больших проектах такой подход предпочтительнее

2023-09-30 09:08 UTC, antonDedyaev commented on src/components/accordion/accordion.pug
> +				+accordion-item(val)
Поправил.

2023-10-02 06:21 UTC, VitoBravis approved these changes
Зачтено 👍

2023-10-02 06:21 UTC, closed without merging