Гасанов Амин.Task 2
only-digital/internship-tasks pull request #98
Opened 2023-09-29 20:14 UTC by lolotron02

Надеюсь на замечания по всем мелким ошибкам, особенно по семантике). В link-3 я использовал <button> для всей компоненты, но мне кажется, что с семантической точки зрения это не верно, и следовало бы использовать тег <a>. Однако в данном случае стилизацию disabled нужно было бы передавать через переменные и использовать if. Поэтому я оставил <button> и добавил стилизацию через селектора :disabled.

2023-10-02 09:31 UTC, VitoBravis requested changes
Надо поправить верстку

2023-10-02 09:31 UTC, VitoBravis commented on src/components/button-container/button-0/button-0.pug
> +			+svg("button-0-svg")(class="button-0__icon")
Согласно спецификации HTML5, тег `<button>` должен содержать только строчные элементы

2023-10-02 09:31 UTC, VitoBravis commented on src/components/button-container/button-0/button-0.scss
> +	&_disabled:disabled {
Нет необходимости в классах-модификаторах для обозначения hover, active и т.д
Эти состояния всегда являются частью основной кнопки независимо от дополнительных css-классов

2023-10-02 09:31 UTC, VitoBravis commented on src/components/button-container/button-1/button-1.scss
> +	width: 169px;
Ограничение ширины и высоты кнопки плохо скажется на универсальности компонента
Размеры кнопки должны складываться из размера контента и внутренних отступов иначе возможна ситуация, в которой текст не будет приспособлен для кнопки
![](http://dl3.joxi.net/drive/2023/10/02/0042/1836/2770732/32/9719ff5dc0.jpg)

2023-10-02 09:31 UTC, VitoBravis commented on src/components/button-container/switch-button-4/switch-button-4.pug
> +	button.switch-button-4&attributes(attributes)(class="switch-button-4_hover switch-button-4_focus switch-button-4_disabled")
Переключатель должен переключать свое состояние. Для этого стоит использовать стандартный элемент браузера:
[`<input type="checkbox">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)

2023-10-02 09:33 UTC, VitoBravis requested changes

2023-10-02 09:33 UTC, VitoBravis commented on src/components/button-container/link-3/link-3.pug
> +		+svg("link-3-svg")(class="link-3__icon")
Этот элемент является ссылкой, он должен быть выполнен в виде тега `<a>`

2023-10-02 19:56 UTC, lolotron02 commented
Есть сомнения что switch-button-4 мог лучше сделать и так-же подходит ли решения которое я применил для link-3

2023-10-03 06:18 UTC, VitoBravis approved these changes
Зачтено 👍

2023-10-03 06:18 UTC, closed without merging